# this is helm chart values.yaml, which will create argocd 'projects' + 'applications'      
projects: {}
# projects:

#   cluster-config:
#     annotations:
#       project: cluster-config
#     labels:
#       project: cluster-config
#     description: Project for overall cluster configuration
#     namespace: openshift-gitops
#     sourceRepos:
#     - '*'
#     destinations: |
#       - namespace: '*'
#         server: https://kubernetes.default.svc
#     extraFields: |
#       clusterResourceWhitelist:
#       - group: '*'
#         kind: '*'

applications: 
# Basics
  openshift-config:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-config      
    source:
      path: clusters/hub/overlays/openshift-config

  reflector-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: reflector-operator      
    source:
      path: components/reflector-operator      

# Networking
  # metallb-configuration:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '6'
  #   destination:
  #     namespace: metallb-system
  #   source:
  #     path: clusters/hub/overlays/metallb-configuration

  # nmstate-configuration:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '6'
  #   destination:
  #     namespace: metallb-system
  #   source:
  #     path: clusters/hub/overlays/nmstate-configuration  

# Storage
    

# ACM
  acm-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
    source:
      path: components/acm-operator

  acm-instance:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: components/acm-instance


  acm-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '25'
    source:
      path: components/acm-configuration

  # acm-observability:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '25'
  #   source:
  #     path: components/acm-observability

  gitops-boostrap-policy:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    namespace: acm-policies  
    source:
      path: components/gitops-boostrap-policy

# DR              

# AAP          

  # aap-operator:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '5'
  #   source:      
  #     path: components/aap-operator

  # aap-configuration:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: aap
  #   source:
  #     path: components/aap-configuration

# MTV     

  # mtv-operator:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '5'
  #   source:
  #     path: components/mtv-operator

  # mtv-configuration:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: openshift-mtv
  #   source:
  #     path: components/mtv-configuration

  # ova-server:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '25'
  #   source:
  #     path: clusters/hub/overlays/ova-server

# Managed Clusters

  # ocp3m0w-ic4s17:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '25'
  #   destination:
  #     namespace: ocp3m0w-ic4s17
  #   source:
  #     path: clusters/hub/overlays/cluster-ocp3m0w-ic4s17

  # etl6:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '25'
  #   destination:
  #     namespace: etl6
  #   source:
  #     path: clusters/hub/overlays/cluster-etl6

     

   